version = 1

[[annotations]]
path = "**"
SPDX-FileCopyrightText = "2024-2026 Gustav Olaf Yunus Laitinen-Fredriksson Lundstrom Imanov <olaf.laitinen@su.se>"
SPDX-License-Identifier = "EUPL-1.2"

[[annotations]]
path = "data/synthetic/**"
SPDX-FileCopyrightText = "2024-2026 Gustav Olaf Yunus Laitinen-Fredriksson Lundstrom Imanov <olaf.laitinen@su.se>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "data/crosswalks/**"
SPDX-FileCopyrightText = "2024-2026 Gustav Olaf Yunus Laitinen-Fredriksson Lundstrom Imanov <olaf.laitinen@su.se>"
SPDX-License-Identifier = "EUPL-1.2"

[[annotations]]
path = "docs/*.md"
SPDX-FileCopyrightText = "2024-2026 Gustav Olaf Yunus Laitinen-Fredriksson Lundstrom Imanov <olaf.laitinen@su.se>"
SPDX-License-Identifier = "CC-BY-4.0"
